import {
    DeviceEventEmitter
} from 'react-native';

export default {
    DEM:DeviceEventEmitter,
    SWITCH_TRANSLATE: "SWITCH_TRANSLATE/切换翻译",
    OPEN_CHAT:"OPEN_CHAT/打开聊天",
    SEND_MESSAGE:"SEND_MESSAGE/发送消息",
    SEND_MESSAGE_STATUS:"SEND_MESSAGE_STATUS/发送消息状态",
    //socket
    SOCKET_CONNECT_ERROR:"SOCKET_CONNECT_ERROR/socket连接错误",
    SOCKET_CONNECT_CLOSE:"SOCKET_CONNECT_CLOSE/socket连接关闭",
    SOCKET_CONNECT_LOADING:"SOCKET_CONNECT_LOADING/socket连接中",
    SOCKET_CONNECT_SUCCESS:"SOCKET_CONNECT_SUCCESS/socket连接成功",
    SOCKET_CONNECT_STATUS:"SOCKET_CONNECT_SUCCESS/socket连接状态",
    SOCKET_LOGIN_LOADING:"SOCKET_LOGIN_LOADING/登录中",
    SOCKET_LOGIN_SUCCESS:"SOCKET_LOGIN_SUCCESS/登录成功",
    SOCKET_LOGIN_FAILED:"SOCKET_LOGIN_FAILED/登录失败",
    SOCKET_LOGIN_BEFORE:"SOCKET_LOGIN_BEFORE/登录后再操作",
    SOCKET_LOGOUT_LOADING:"SOCKET_LOGIN_FAILED/退出中",
    SOCKET_LOGOUT_SUCCESS:"SOCKET_LOGIN_SUCCESS/退出成功",
    SOCKET_LOGIN_REPEAT:"SOCKET_LOGIN_REPEAT/重新登录",
    SOCKET_CHAT:"SOCKET_CHAT/聊天",
    SOCKET_USERTYPING:"SOCKET_USERTYPING/用户输入中",
    SOCKET_NOTIFICATION:"SOCKET_NOTIFICATION/消息通知",
    SOCKET_CONNECT:"SOCKET_CONNECT/连接",
    //socket
    MARK_AS_READ:"MARK_AS_READ/消息阅读",
    NOTIFICATION_ALL:"NOTIFICATION_ALL/所有消息",
    DELETE_CONVERSATION:"DELETE_CONVERSATION/删除谈话",
    TRANSLATE_SEND:"TRANSLATE_SEND/翻译后发送",
    TRANSLATE_RETURN:"TRANSLATE_RETURN/翻译回退",
    //声音播放
    VOICE_NAV_SWITCH:"VOICE_NAV_SWITCH/导航切换",
    VOICE_NEW_MESSAGE:"VOICE_NEW_MESSAGE/有消息到",
    VOICE_MESSAGE_REFRESH_FINISH:"VOICE_MESSAGE_REFRESH_FINISH/消息列表刷新完成",
    VOICE_MESSAGE_READY:"VOICE_MESSAGE_READY/消息准备刷新",
    VOICE_MESSAGE_BEFORE_SEND:"VOICE_MESSAGE_BEFORE_SEND/消息发送前",
    VOICE_MESSAGE_FINISH_SEND:"VOICE_MESSAGE_FINISH_SEND/消息发送完成",
    AJAX_LOGIN_SUCCESS:"AJAX_LOGIN_SUCCESS/异步登录成功,切换界面",
    TRANSLATE_POPOVER:"TRANSLATE_POPOVER/点击消息进行翻译或其它",
    AJAX_LOGIN_403:"AJAX_LOGIN_403/需要ajax重新登录",
    MESSAGE_CHAT_BACKMESSAGES:"MESSAGE_CHAT_BACKMESSAGES/从聊天返回聊天列表"
}